<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-25T10:02:07 IST" name="Default suite" finished-at="2023-08-25T10:02:33 IST" duration-ms="26558">
    <groups>
    </groups>
    <test started-at="2023-08-25T10:02:07 IST" name="Default test" finished-at="2023-08-25T10:02:33 IST" duration-ms="26558">
      <class name="FinalScriptVtiger.CreateEventTest">
        <test-method is-config="true" signature="classSetup()[pri:0, instance:FinalScriptVtiger.CreateEventTest@15de0b3c]" started-at="2023-08-25T10:02:07 IST" name="classSetup" finished-at="2023-08-25T10:02:10 IST" duration-ms="3735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetup -->
        <test-method is-config="true" signature="methodSetup()[pri:0, instance:FinalScriptVtiger.CreateEventTest@15de0b3c]" started-at="2023-08-25T10:02:10 IST" name="methodSetup" finished-at="2023-08-25T10:02:21 IST" duration-ms="10506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetup -->
        <test-method signature="createEventtest()[pri:0, instance:FinalScriptVtiger.CreateEventTest@15de0b3c]" started-at="2023-08-25T10:02:21 IST" name="createEventtest" finished-at="2023-08-25T10:02:21 IST" duration-ms="225" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "String.contains(java.lang.CharSequence)" because "toEscape" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "toEscape" is null
at org.openqa.selenium.support.ui.Quotes.escape(Quotes.java:42)
at org.openqa.selenium.support.ui.Select.findOptionsByValue(Select.java:289)
at org.openqa.selenium.support.ui.Select.selectByValue(Select.java:194)
at GenericLibraries.WebdriverUtility.selectFromDropdown(WebdriverUtility.java:173)
at PomPages.HomePage.selectFromquiteCreate(HomePage.java:49)
at FinalScriptVtiger.CreateEventTest.createEventtest(CreateEventTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEventtest -->
        <test-method is-config="true" signature="methodTearDown()[pri:0, instance:FinalScriptVtiger.CreateEventTest@15de0b3c]" started-at="2023-08-25T10:02:21 IST" name="methodTearDown" finished-at="2023-08-25T10:02:33 IST" duration-ms="11685" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
        <test-method is-config="true" signature="classTearDown()[pri:0, instance:FinalScriptVtiger.CreateEventTest@15de0b3c]" started-at="2023-08-25T10:02:33 IST" name="classTearDown" finished-at="2023-08-25T10:02:33 IST" duration-ms="271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTearDown -->
      </class> <!-- FinalScriptVtiger.CreateEventTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
